### ISSUE TITLE
怎样显示多个snackbar，显示一条消息再来一条消息会把之前的覆盖掉

### ISSUE THREAD

**Issue by y2653904** [guoyoujin/MySnackBar#12]

**Comment by guoyoujin** [comment]
如果要实现你这个需求的话，就需要做一个消息队列了，每次来一个显示都要压入栈里面，等待前一个窗口显示完成后，在根据先进先出的规则，显示消息，这样的话，只需要暴露一个onDismiss()和OnShow()接口就能实现你说的功能，当走到onDismiss方法的时候把显示过的消息清除，并显示新的消息即可
