### ISSUE TITLE
仓库的版本在某些华为机型有BUG

### ISSUE THREAD

**Issue by Null-Ouwenjie** [guoyoujin/MySnackBar#3]
Hi~
刚使用 compile 'com.trycatch.android:mysnackbar:1.1.11' 的库，发现在华为荣耀6机子（API 19）上会覆盖整个屏幕，应该是 setMinHeight () 造成的，但我没有找到代码异样的地方...
而 GitHub 中的库则不会造成覆盖全屏的BUG..

**Comment by guoyoujin** [comment]
你是指你跑我这个demo的时候不回出现这个情况，但是，在你的项目里面使用这个库的时候会出现这个问题，对吗？

**Comment by Null-Ouwenjie** [comment]
@guoyoujin 嗯，对的。

**Comment by guoyoujin** [comment]
可能出现这个问题的原因是layout文件夹下的```view_tsnackbar_layout.xml```文件
<view xmlns:android="http://schemas.android.com/apk/res/android"
    class="com.trycatch.mysnackbar.TSnackbar$SnackbarLayout"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="top"
    style="@style/Widget.Design.Snackbar" />
他的``` android:layout_height="wrap_content"```被设置成了```match_parent```
我测试的时候有出现这个问题就是由这个导致的

**Comment by Null-Ouwenjie** [comment]
OK 😄
