### ISSUE TITLE
在NOActionBar等主题中文字为黑色的，而且修改不了颜色，如果改了主题颜色，本就写好的界面又大乱

### ISSUE THREAD

**Issue by aesion** [guoyoujin/MySnackBar#4]
很严重的问题，希望可以把文字颜色一直为白色

**Comment by aesion** [comment]
TSnackbar.SnackbarLayout view = (TSnackbar.SnackbarLayout) snackBar.getView();
view.getMessageView().setTextColor(Color.GREEN);
这个方法可以解决但是必须修改源码里面的getMessageView方法为Public，希望作者改下源码，然后可以重新compile

**Comment by guoyoujin** [comment]
好的马上解决你这个问题

**Comment by guoyoujin** [comment]
@aesion  
方法已经提供
`setActionTextColor()    |  设置button按钮字体颜色
setActionTextSize()    |  设置button按钮字体大小
setMessageTextSize    |  设置提示语按钮字体大小
setMessageTextColor    |  设置提示语按钮字颜色`

**Comment by aesion** [comment]
非常感谢，已使用至项目
