### ISSUE TITLE
被虚拟按键覆盖的问题

### ISSUE THREAD

**Issue by flyingshare** [guoyoujin/MySnackBar#6]
有虚拟按键的机型，设置从底部弹出的时候，被虚拟按键覆盖了

**Comment by guoyoujin** [comment]
好的，晚上测试下

**Comment by guoyoujin** [comment]
@flyingshare 关于虚拟键盘问题你可以使用如下代码：
下面这个代码是不遮挡虚拟键盘并显示在虚拟键盘上面，主要代码就是   `findViewById(android.R.id.content)`即让Snackbar依附在那个view上面显示
 `TSnackbar.make(findViewById(android.R.id.content), "正在登录，请稍后...", TSnackbar.LENGTH_INDEFINITE, TSnackbar.APPEAR_FROM_BOTTOM_TO_TOP);`
