### ISSUE TITLE
有时候不弹出提示

### ISSUE THREAD

**Issue by libeimarch** [guoyoujin/MySnackBar#8]
有时候不弹出提示,不知道是为什么。 状态都正常的,有时候就是不弹出提示。 关闭重启后又正常。少数情况出现,请问这种情况你能猜测出什么原因吗?

**Comment by guoyoujin** [comment]
因为使用的是官方的snackBar单例模式，所以会出现当前一个打开的snackBar未关闭的话就会出现这个情况，一般这个情况都是出现在页面之间的切换，解决这个问题的办法就是，在调用show方法的时候先关闭之前打开的snackBar
